server:
  port: 8080
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 20MB
      max-request-size: 20MB
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: SNAKE_CASE

  couchbase:
    bucket:
      name: demo
      password: shakti@123
    bootstrap-hosts: localhost
    port: 8091
    username: Administrator

#custom properties
carrier-name: SHADOWFAX
carrier-service: SHADOWFAX-SURFACE